// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "model": string;
      "systemPrompt": string;
      "presets": string;
      "selectedPresets": string;
      "enable": boolean;
      "input": string;
    };
  }
}
